# configs/config.yaml

# Hydra configs
hydra:
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    handlers:
      file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers: [file]

# ---------------------------------------------------------------------------------------------------
# Main configs
dataset:
  # available datasets: conic, consep, cpm15, cpm17, cryonuseg, kumar, monusac, monuseg, nucls, nuinsseg, ocelot, pannuke
  name: "conic"
  path: "/mnt/vol3/Datasets/CoNIC/data/"
  saved_images: true

model:
  name: "resnet18"
  pretrained: true

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001

other:
  log_print: false